Sprint.2.12. Add video recording for failed tests for both local and CI runs
DragonPWJur/DragonJur pull request #15
Opened 2024-01-08 06:26 UTC by YuliaMatusevich

- Add video recording for failed tests for both local and CI runs;
- The mechanism for enabling and disabling of tracing and video recording is implemented in the config.properties and ci.yml;
- Add 'videos' folder to .gitignore.

2024-01-08 15:43 UTC, IriSamo approved these changes
LGTM!

2024-01-08 16:40 UTC, ViktoriyaED approved these changes

2024-01-09 05:36 UTC, ArinaJur requested changes

2024-01-09 05:36 UTC, ArinaJur commented on src/test/java/utils/ReportUtils.java
> +    public static String getReportHeader(ITestContext testContext) {
Please refactor this method using ProjectConstants

2024-01-09 06:10 UTC, ArinaJur commented on src/test/java/utils/ReportUtils.java
> +    public static String getReportHeader(ITestContext testContext) {
These changes will be included in a separate PR.

2024-01-09 11:00 UTC, SafronovaOlga approved these changes

2024-01-09 17:51 UTC, merged