Sprint 2. TC1349 - User can mark cards for re-checking TC1350-01 User can mark the card TC1350-02 After marking the card, the number of marked cards increased by 1.
DragonPWJur/DragonJur pull request #17
Opened 2024-01-11 02:27 UTC by LaysanNova

Sprint 2. TC1349 - User can mark cards for re-checking
!class TestTutorPage > method clickAddToFlashCard
TC1350-01 User can mark the card
TC1350-02 After marking the card, the number of marked cards increased by 1.

2024-01-11 18:46 UTC, ArinaJur requested changes

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/BaseLocator.java
> +    protected void clickSubject(String subject) {
This is not a generic method. Please put it into the POM class where you use it (FlashcardsPage, etc)

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/FlashcardsPage.java
> +    public Locator markedForRechecking = getPage().getByRole(AriaRole.BUTTON)
All locators should remain private final.

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/FlashcardsPage.java
> +            .filter(new Locator.FilterOptions().setHas(getPage().getByText("Marked for re-checking")));
Please try to refactor this lines to something like "button().filter("Marked for re-checking")"

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/FlashcardsPage.java
> +    public Locator numberMarkedForRechecking = getPage().getByRole(
Is it possible to use "button("Marked for re-checking").locator("//div[2]");" ?

Also please try to refactor "//div[2]" to CSS selector.

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/FlashcardsPage.java
> +    public Locator flashcardsMenuButton = button("Flashcards");
Let's refer to this as flashcardsMenu

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/FlashcardsPage.java
> +    public FlashcardsPage clickFlashcardsMenuButton() {
clickFlashcardsMenu()

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/TestTutorPage.java
> +    public Locator closeTestButton = exactButton("Close the test");
Please make all locators private final

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/TestTutorPage.java
> +    public Locator removeFromFlashcards = button("Remove from flashcards");
rremoveFromFlashcardsButton

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/TestTutorPage.java
> +    public Locator markForReview = button("Mark for review");
markForReviewButton

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/TestTutorPage.java
> +    public Locator removeFromMarked = button("Remove from marked");
removeFromMarkedButton

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/TestTutorPage.java
> +    public Locator closeTestButton = exactButton("Close the test");
closeTheTestButton

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/TestTutorPage.java
> +    public TestTutorPage clickAddToFlashCard() {
clickAddToFlashCardButton()

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/TestTutorPage.java
> +    public void clickCloseTestButton() {
clickCloseTheTestButton()

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/TestsPage.java
> +    public Locator promptMessageUnfinishedTest  = text("You have unfinished test. Do you want to continue?");
Please make all locators private final

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/TestsPage.java
> +    public Locator testsMenuButton = button("Tests");
testsMenu

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/TestsPage.java
> +    public Locator numberOfQuestions = textBox();
numberOfQuestionsTextBox

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/TestsPage.java
> +    public Locator generateStartButton = button("Generate & Start");
generateAndStartButton

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/TestsPage.java
> +    public Locator cancelButtonOnPromptWindow = button("Cancel");
cancelButton

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/TestsPage.java
> +    public Locator promptMessageUnfinishedTest  = text("You have unfinished test. Do you want to continue?");
unfinishedTestText

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/TestsPage.java
> +        List<Locator> subjects = getPage().locator("div.sc-gHnmx.iEQmLh").all();
Please move this to locators fields

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/TestsPage.java
> +        String text = getRandomValue(subjects).textContent();
It is better to use TestUtils.getRandomValue()

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/TestsPage.java
> +    protected String catchSubject() {
getSubject()

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/pages/TestsPage.java
> +    public void initiateTest() {
This method should be refactored to use smaller test scenario steps

clickTestsMenu()
dismissPromptIfShown()
clickSubject(getSubject())
inputNumberOfQuestions()
clickGenerateAndStartButton()

etc

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/tests/TestsTest.java
> +    public String preconditions_1349() {
This method should be moved to the POM and given a name that clearly describes its purpose (for ex getNumberOfCardsBeforeTestStarted)

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/tests/TestsTest.java
> +    public void test_1349() {
Please name the tests according to the corresponding test case name.

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/tests/TestsTest.java
> +        Locator newNumberOfCardsForReChecking = new FlashcardsPage(getPage(), getPlaywright()).clickFlashcardsMenuButton().numberMarkedForRechecking;
After refactoring the code above, we should reconsider the test format.

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/tests/TestsTest.java
> +        assertThat(newNumberOfCardsForReChecking).hasText(Integer.toString(parseInt(numberOfCardsForReChecking) + 1));
Please always remove actions or calculations from assert

2024-01-11 18:46 UTC, ArinaJur commented on src/test/java/utils/TestUtils.java
> +    public static  <T> T getRandomValue(List<T> listValues) {
It should be a separate PR

2024-01-11 19:16 UTC, LaysanNova commented on src/test/java/pages/TestsPage.java
> +    public Locator promptMessageUnfinishedTest  = text("You have unfinished test. Do you want to continue?");
не совсем поняла

2024-01-12 20:40 UTC, LaysanNova commented
не актуально

2024-01-12 20:40 UTC, LaysanNova commented
не актуально

2024-01-12 20:40 UTC, closed without merging