Sprint 2. TC1361-01 - Typing of not found text gives “Nothing found. Try to use other keywords” message.
DragonPWJur/DragonJur pull request #30
Opened 2024-01-13 09:23 UTC by NataliiaBor1

TC1361-02 - Displaying All Matches for the Searched Keyword

2024-01-14 00:54 UTC, ArinaJur requested changes
Please create 2 RPs for each tests/ We have a strict rule "1 test in 1 PR"

2024-01-16 09:14 UTC, NataliiaBor1 commented
@ArinaJur I made a changes, and only TC-1361-01 was left in this PR. Please, check.

2024-01-17 20:15 UTC, ArinaJur approved these changes
LGTM

2024-01-17 20:15 UTC, verafes approved these changes

2024-01-17 20:15 UTC, merged