Sprint 3. TC1345 running timed
DragonPWJur/DragonJur pull request #45
Opened 2024-01-15 06:43 UTC by RustamKhudoyarov

-- added test - testRunTimedMode()
-- added class TestTimedPage with methods for the test testRunTimedMode()
-- added methods to class TestListPage for the test testRunTimedMode()
-- added test data for the test to class TestData
-- refactor:  added condition into cancelDialogIfVisible() because tests failed - waiting locator.

2024-01-15 07:48 UTC, ArinaJur requested changes

2024-01-15 07:48 UTC, ArinaJur commented on src/test/java/pages/TestListPage.java
> +    private final Locator startTButtonModalWindowWithQuestions = exactButton("Start");
Please name this locator startButton

2024-01-15 07:48 UTC, ArinaJur commented on src/test/java/pages/TestListPage.java
> +    public TestListPage clickStartTestButtonModalTimedTest() {
Please name this method clickStartTestButton

2024-01-15 07:48 UTC, ArinaJur commented on src/test/java/pages/TestListPage.java
> +    public TestTimedPage clickStartOnTheModalWindowWithQuestions() {
Please name this method clickStartButton

2024-01-15 07:48 UTC, ArinaJur commented on src/test/java/pages/TestListPage.java
> +    public TestListPage clickGenerateStartButton() {
Please name clickGenerateAndStartButton()

2024-01-15 07:48 UTC, ArinaJur commented on src/test/java/pages/TestTimedPage.java
> +    private final Locator textQuestionMark = text(TestData.QUESTION_MARK);
This is not a test class. We can't use test data in POM. Test data can change. Please use the exact text here

2024-01-15 07:48 UTC, ArinaJur commented on src/test/java/pages/TestTimedPage.java
> +        List<Locator> radioButtons = new ArrayList<>();
please move
private final List<Locator> radioButtons = radio(); 
to locators (top of this page)

then do 
public int getAnswersCount() {
   return radioButtons.size();
}

2024-01-15 07:48 UTC, ArinaJur commented on src/test/java/pages/TestTimedPage.java
> +    private final Locator radioButtonLocator = radio();
On this page it could be more then one radio  locators
Please do
private final List<Locator> radioButtons = radio();

2024-01-15 07:48 UTC, ArinaJur commented on src/test/java/pages/TestTimedPage.java
> +    private final Locator timerOnTimedTest = locator("header div div:has(button)>div");
Please name it "timer" since we have the only timer element on this page

2024-01-15 07:48 UTC, ArinaJur commented on src/test/java/pages/TestTimedPage.java
> +    private final Locator textQuestionMark = text(TestData.QUESTION_MARK);
Please name it questionMarkText

2024-01-15 19:05 UTC, RustamKhudoyarov commented on src/test/java/pages/TestListPage.java
> +        }
Он переодически падает, если используется  cancelDialog();

2024-01-15 19:27 UTC, RustamKhudoyarov commented on src/test/java/pages/TestListPage.java
> +    public TestListPage clickGenerateStartButton() {
Этот метод уже есть и он работает не верно возвращается не верный тип страницы, для моего случая должен вернуть TestListPage, а существующий метод работает либо не верно, либо этот метод мне не подходит. Нужно возвращать другую страницу.

2024-01-15 20:30 UTC, RustamKhudoyarov commented on src/test/java/pages/TestListPage.java
> +        }
проверка до использования метода тоже не помогает. Он ищет на странице waiting for getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Cancel")) 
Не зависимо от условия, что диалоговое окно видно или нет.

2024-01-15 21:48 UTC, ViktoriyaED commented on src/test/java/pages/TestTimedPage.java
> +public class TestTimedPage extends SideMenuPage {
Рустам, страницу TestTimedPage нужно отнаследовать от TestTutorPage, так как они практически повторяют друг друга. Страница tutorTimedPage содержит  на несколько элементов больше

2024-01-15 21:56 UTC, RustamKhudoyarov commented on src/test/java/pages/TestTimedPage.java
> +public class TestTimedPage extends SideMenuPage {
Они никак логически не связаны... Это разные объекты. Более верно отнаследовать от SideMenu или TestsListPage, но никак не от TestTutorPageю Это вообще две параллельные сущности. И не важно, что у них одинаковые признаки, тогда нужно создавать базовую страницу с наличием общих методов и наследовать для обеих траниц...

2024-01-15 22:21 UTC, ArinaJur commented
Please also rename your PR. Your test case name is

TC1345-01 - Execute Timed Mode with a randomly selected checkbox in the Chapter section

2024-01-15 22:43 UTC, ArinaJur requested changes

2024-01-15 22:43 UTC, ArinaJur commented on src/test/java/pages/TestListPage.java
> +    private final Locator startTButton = exactButton("Start");
extra T letter in the name

2024-01-15 22:43 UTC, ArinaJur commented on src/test/java/pages/TestTimedPage.java
> +    private final List<Locator> radioButtons = new ArrayList<>();
Please change

private final List<Locator> radioButtons = radio().all();

2024-01-15 22:43 UTC, ArinaJur commented on src/test/java/pages/TestTimedPage.java
> +    public int getAnswersCount() {
Please change 

public int getAnswersCount() {

        return radioButtons.size();
    }

2024-01-15 22:43 UTC, ArinaJur commented on src/test/java/pages/TestTimedPage.java
> +    private final Locator radioButtonLocator = radio();
Please delete this locator

2024-01-15 23:08 UTC, ArinaJur approved these changes
Thanks!

2024-01-15 23:26 UTC, ArinaJur requested changes

2024-01-15 23:26 UTC, ArinaJur commented on src/test/java/tests/TestListTest.java
> +
Please add 
waitForPageLoad(BASE_URL + TestData.TEST_TIMED_END_POINT);
on line 60

2024-01-16 05:03 UTC, ArinaJur requested changes

2024-01-16 05:03 UTC, ArinaJur commented on src/test/java/pages/TestTimedPage.java
> +    private final Locator radioButtons = waitForLocatorOfElementsLoaded(radio());
Please change it to radio().all() and please remove waitFor into the method where you need it

2024-01-16 13:00 UTC, ArinaJur approved these changes

2024-01-16 16:03 UTC, ViktoriyaED approved these changes

2024-01-16 21:27 UTC, merged