Sprint 1. TC1344-01 - Execute Tutor Mode with randomly selected checkbox in Domain section
DragonPWJur/DragonJur pull request #5
Opened 2024-01-03 05:30 UTC by ViktoriyaED

TC1344-01 Create test + Execute Tutor Mode with randomly selected checkbox in Domain section

2024-01-11 06:13 UTC, ArinaJur requested changes

2024-01-11 06:13 UTC, ArinaJur commented on src/test/java/tests/TestListTest.java
> +        String expectedNumberOfQuestions = "1";
Please make both parameters final. 
Even better, create a TestData class and move them. This test data will be reused in other tests.

2024-01-12 01:48 UTC, IriSamo approved these changes

2024-01-12 01:48 UTC, ArinaJur approved these changes
Good! Thank you!

2024-01-12 01:59 UTC, merged