Sprint 4. TC1361-01 was refactored to new POM
DragonPWJur/DragonJur pull request #93
Opened 2024-01-23 20:32 UTC by NataliiaBor1

testSearchByNotExistingKeyWord was refactored to new POM.

2024-01-23 21:48 UTC, ArinaJur requested changes

2024-01-23 21:48 UTC, ArinaJur commented on src/test/java/tests/SearchTest.java
> +        StudyGuidePage studyGuidePage = new HomePage(getPage()).init()
Начиная со слова new перенесите на другую строчку, пожалуйста чтобы было видно, что цепочка начинается с HomePage

2024-01-23 21:48 UTC, ArinaJur commented on src/test/java/tests/SearchTest.java
> +        assertThat(studyGuidePage.getSearchResultField()).hasText(Constants.NOTHING_FOUND_MESSAGE);
Сообщение NOTHING_FOUND_MESSAGE должно быть продублировано в TestData. тк константы задают состояние системы, а тестовые данные проверяют, что состояние системы правильное. ПОтому константы - только в POM, а в тестах - только TestData

ВСе остальное - прекрасно

2024-01-24 17:27 UTC, ArinaJur approved these changes
LGTM

2024-01-24 17:27 UTC, LiudmilaPlucci approved these changes

2024-01-24 17:28 UTC, merged